version: '2.1'
services:
  mysql:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=ffbetdatabase
    - MYSQL_USER=root
  ffb_daw_fase3:
    image: ffb/ffb_daw_fase3
    depends_on:
    - mysql
    ports:
    - 8080:8080
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=pass
    - DATABASE_NAME=ffbetdatabase
    - DATABASE_PORT=3306

